### ISSUE TITLE
Security exception while using the Download Link and Admin Tools

### ISSUE THREAD

**Issue by tampe125** [akeeba/release-system#122]
If we have Admin Tools installed and the feature *Disable creating / editing backend users from the frontend* enabled, if a Super User tries to download something he raises a security exception.

Drilling into the code, this is caused by ARS trying to set and save the last visit time inside the user. Since we're using Joomla API, the whole chain of events is triggered, Admin Tools intercepts the `onUserBeforeSave` event and blocks the request since the user is a Super User.

To avoid this we have to use a direct query on the database.

**Comment by nikosdion** [comment]
No, the bug is in Admin Tools. If the only thing being changed is the last visited timestamp, the blocked flag, the token for the password reset or the two factor authentication parameters we must *not* trigger the protection. These are all valid changes.

Please fix that in Admin Tools and add test cases. Actually, add the (failing) tests first, then make the changes to make sure the tests pass. This will prevent any similar issues.

FWIW this explains some weird issues some clients had in the past. Apparently we're not the only extension to modify the last visited timestamp.

**Comment by tampe125** [comment]
Closed, see akeeba/admintools#134
