### ISSUE TITLE
Issues with "ARS Item" editor button

### ISSUE THREAD

**Issue by Bakual** [akeeba/release-system#126]
I noticed that there are two issues with the "ARS Item" editor button:
* Really minor one: It doesn't show an icon. Maybe that is even intentional, I don't know. 
![image](https://user-images.githubusercontent.com/1018684/30807008-50e14410-a1f8-11e7-9c04-9df271489383.png)
* Major one: When trying to select an item to insert into an article, nothing happens. Chrome Console shows the following JS errors:
![image](https://user-images.githubusercontent.com/1018684/30807077-a6f68a40-a1f8-11e7-9bb8-8875172a980b.png)

**Comment by nikosdion** [comment]
Both of these issues were due to undocumented, backwards incompatible changes in the default WYSIWYG editor. These issues could not be reproduced with other third party editors such as JCE.

The icon did not appear because someone changed the icon element from a semantically correct `<span>` to a semantically _incorrect_ `<i>`. The CSS we were producing was only targeting the former. Remember that Joomla! did change all `<i>` to `<span>` about five years ago for semantic reasons. Also note that it only happens in the core TinyMCE instance when `editor-xtd` plugins are rendered inline the toolbar. When the plugin buttons are rendered below the editor `<span>` are used and this issue does not occur. So, if you ask me, I would consider this a Medium-High priority bug in Joomla! and I applied a workaround.

Regarding the second issue, the JavaScript error occurred within the editor's JavaScript, not the ARS code. I could also not reproduce it with other third party editors. Looking around it seems that the core editor has decided to use a backwards incompatible API (`Joomla.editors.instances[editor].replaceSelection(tag)`) to insert text into the editor. In theory, using `jInsertEditorText(tag, editor)` should have the same effect. After all, the latter is the only API reasonably expected to be available to third party editors. However, the implementation of `jInsertEditorText` in the core TinyMCE instance is borked, causing the JavaScript error you experienced. If you ask me that's a High priority bug in Joomla! and I applied a workaround.

My suggestion would be to file bug reports with Joomla! about these bugs in the editor API. They seem to have been around for several months. Even the core `editor-xtd` plugins ran into them and now have ugly if-blocks to figure out which API they should be using to insert raw HTML into the editor.

**Comment by Bakual** [comment]
Yes, having `<i>` for the icon sounds like a bug to me as well. There was a reason it got changed to `<span>`.
I'm going to open issue for Joomla then (later). I agree with you it looks like B/C breaks in the API.

**Comment by dgt41** [comment]
@nikosdion the `<i>` is created on tinyMCE init and we don't have much options here...

About the new API: should only be used if the XTD-button actually implements it otherwise the one function rules them all is still there, or at least _should be there_

**Comment by nikosdion** [comment]
The “should be there” is the catch. The function is there but it bombs out in the core-provided TinyMCE editor. It works in JCE. The new API works in the core-provided TinyMCE editor but fails on everything else. 

So, it seems that the one function to rule them all is buggy in the core-provided TinyMCE editor, making it a b/c issue :)
