### ISSUE TITLE
Browsing S3 to Link Files Does not work

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#128]
Under a previous version of the app, a user could browse the Amazon S3 server to find the item file. The current version 3.2.5 just shows a link which does nothing.

**Comment by nikosdion** [comment]
You can replace the files referenced in https://github.com/akeeba/release-system/commit/ab21f33a103674f6cdfdeb2e16539846a66f1bc8 manually to fix that on your site

**Comment by murphylas** [comment]
This does not work. If there are files in a folder. Then ARS lists the files and allows the user to select a file. If there are NO files or there are ONLY folders in a folder, it does nothing. It does not allow the user to click on a folder to browse to the folder. In other words the browse capability does not work. The old version of ARS had this ability. You could type in the path and ARS would list the files in that path. ARS version 2.5.1 had this ability.

**Comment by nikosdion** [comment]
The only feature I am interested in supporting is the file selection drop-down in the Item edit view. This was broken and fixed with https://github.com/akeeba/release-system/commit/ab21f33a103674f6cdfdeb2e16539846a66f1bc8. As it has always been the intention, the supported layout of your S3 bucket is meant to be `/path/to/root/CATEGORY_FOLDER/SUBFOLDER/FILE` where `/path/to/root` is the folder specified in ARS' Options, `CATEGORY_FOLDER` is the folder specified in the ARS category and `SUBFOLDER` is _exactly zero or one_ folders in which the `FILE` (file to be downloaded) lives. This is fully supported and fixed with the commit I referenced above.

You are probably talking about the Upload view. There are two reasons why this is not going to be touched. For starters, it is marked for removal. There are several shortcomings with using a Joomla extension to deal with uploads, especially when you get to larger files. It's best handling uploads with proper tools on your computer, either GUI (such as FileZilla, Cyberduck etc) or CLI (scp, s3cmd etc). That should be reason enough, especially since we're already in the process of rewriting the GUI since last week and this view is going to go away.

The other reason is that, as I explained, the supported folder structure is the shallow model which currently does work. Your deep structure was never supposed to work. If it did before consider yourself lucky. Like, _really_ lucky because that was a bug! If it returned empty directories it means that it was reading more information than it should. If you had an S3 folder with hundreds of files and tried to access it would probably crap its pants and die with a memory error. That was, indeed, fixed in version 3 since that code also affects how Bleeding Edge works (which did crap its pants with really big S3 directories - which is exactly why it was fixed).
