### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by zibelian** [akeeba/release-system#132]
Hi, 

I have read through your documention where you mention that you dont recommend it as a generic download manager. This is the sentence that got stucked in my head. The questions i am asking, can this extension handle a big and groving catalogue of downloads?

I talking about thousands of downloads, and if your negative recomendation about using it as a generic download manager is about poor perfomance with a larger catalogue of downloads, i would really like to know if this is what your refering to.

How does this compare to for example other download managers on the joomla market, lets say... phoca downloads in regards of perfomance, is it on the same level ? 

I really prefeer akeeba ars over all other download managers i have tried, and its working great for me at the moment, having around 100+ downloads with no issues at all.

I would really like your opinion on this and thank you for letting us use your great work, really appreciated!

**Comment by nikosdion** [comment]
The performance is stellar. We have ten years and over twenty distinct software's worth of downloads in our installation, with millions of downloads every year. The only thing you might want to purge once in a while is the downloads log. After around 500,000 rows MySQL starts getting sluggish unless you can spare some RAM. It's not an ARS design issue, it's just how MySQL works which, in fact, can't be any better; loads of data has to fit _somehow_ in disk and memory!

Compared to other download managers ARS is actually faster :) I have fine tuned the long queries by hand to minimize the memory and CPU used by most common (and several uncommon) operations. The reason is simple. Our site has a massive dataset and needs to be _fast_. So I did what I learned to do in the early 90s when working on memory constrained, slow as heck 80286 DOS boxes: optimize everything by hand and show no mercy. What I've seen in other download managers is that they didn't go to such lengths. They are fast but when the data sets get really big they have unoptimized queries which will boggle your server. For most people that's theoretical. For your use case it might indeed make a difference.

What I meant with that sentence you mentioned is that ARS is designed with an inflexible structure of Category - Release - Item. Most of its features are geared towards publishing software, from automatic item translations to a JSON API. If you're OK with that, sure, use it as a generic download manager. Nobody's gonna stop you. You'll get a really fast download manager with some unique quirks for setting it up, that's all.

**Comment by zibelian** [comment]
Thanks nikosdion for this great info and reply! I'll will stick with Akeeb ARS for a long time, cant be more satsified than i am, once again, really appreciated that you make this extension still available for us.

**Comment by nikosdion** [comment]
You're welcome!
