### ISSUE TITLE
Crashing Website after Item Save

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#137]
Nice job on ARS 4.

When I try to save a very large ARS item usually over 300 MB stored on Amazon S3, I get the following error:

Fatal error: Allowed memory size of 94371840 bytes exhausted (tried to allocate 48250880 bytes) in /home/themannatest/test.themannareserve.org/administrator/components/com_ars/Model/Items.php on line 821

I usually have to insert the actual file size manually and the save works. 

It may have something to do with how Joomla determines file sizes.

**Comment by nikosdion** [comment]
When you try to save an Item in ARS you need to provide file size and the MD5 and SHA1 sums for the file. If you don't, the item has to be downloaded from its storage, loaded in memory and these properties calculated. Since the object you have is larger than the maximum PHP memory limit you get an error.

The solution is to, of course, provide these properties yourself. In this case the item does not need to be downloaded from S3.

**Comment by murphylas** [comment]
Thanks for the info.
