### ISSUE TITLE
Have to select 'Public' To see and select categories

### ISSUE THREAD

**Issue by hrtrulz** [akeeba/release-system#138]
I have to select 'Public' in categories list to be able to see my categories which are public as list keep defaulting to registered. 

In Releases section it will not show release name unless I select 'Public' access level first in list view, if Not I can not select a category in the edit view.

Our site has the 'Default Access Level' set to 'Registered'

**Comment by nikosdion** [comment]
Thank you for the heads up. This is actually a bug with FOF that's been there for the last 3 years. It only affected ARS now because the new version is using the affected FOF feature (Joomla! asset tracking). Please install the latest FOF dev release from https://www.akeebabackup.com/download/developer-releases/fof-dev/rev32757066.html to fix this issue.

**Comment by Mocha365** [comment]
This seems to have worked for me too as I was experiencing a similar issue.
