### ISSUE TITLE
403 when downloading update from ars

### ISSUE THREAD

**Issue by basd82** [akeeba/release-system#171]
After upgrade to 4.2.2 

When a sites try's to download an update it get's an 403 error. what am i doing wrong the download url looks like this 
https://some.domain.tld/component/ars/repository/extention/extention-6-1-12/extention-6.1.12.zip.zip?format=raw&dummy=my.zip

**Comment by nikosdion** [comment]
Your problem is that the Item, the Release or the Category have a limitation which does not allow the update to proceed. For example, if the Category is set to Registered only logged in users (or users using a Download ID) will be able to download the Item _even if_ the Item and the Release themselves are set to Public. 

There was a bug in older versions of ARS where privileges wouldn't cascade correctly. Now that's fixed. The user trying to effect the download must satisfy access control on the Item, the Release and the Category. One does not override the other.
