### ISSUE TITLE
Upload item file by API

### ISSUE THREAD

**Issue by laoneo** [akeeba/release-system#194]
The only task where the build script actually needs an SSH connection to a remote server is to upload the actual release files. Wondering what needs to be done to be able to upload these files with the POST/PATCH request? Something which would be simple is to add a content field with the base64 encoded binary, similar to what we do with the media manager. Any thoughts on this? If this gets some acceptance, I can try to do a pr.

**Comment by nikosdion** [comment]
In theory it should be possible to implement such a feature with a new API controller (otherwise the POST request would collide with the existing code to update an Item; we don’t want that). We’d need to do a PUT request with a multipart form so Joomla can populate the files input.

I would also suggest that this is a separate operation to creating or updating an item so that we maintain separation of concerns.

The only thing I do not know is whether the API application actually supports this kind of POST request. You are welcome to explore that option. I would be very interested in such a feature.

**Comment by nikosdion** [comment]
Have you tried to work on this at all?

**Comment by laoneo** [comment]
Will reopen, when I have time.

**Comment by nikosdion** [comment]
No problem!
