### ISSUE TITLE
Issues updating a Joomla 3 site to Akeeba Release 6

### ISSUE THREAD

**Issue by tassosm** [akeeba/release-system#210]
I am aware that support is not provided but I will give it a try. Maybe I will get lucky.

I have a Joomla 3 site running Akeeba Release 4.2.2. I am planning to upgrade it to Joomla 4, but before doing so, I want to update all the installed extensions to their latest version.

I saw that the latest compatible version of Akeeba Release with Joomla 3, is v6.0.3 which I used to update my site.

While the Akeeba Release backend works pretty good, on the front-end when I try to access the Releases page I end up with the following error:

`Class 'AkeebaFEFHelper' not found /var/www/site.com/components/com_ars/Dispatcher/Dispatcher.php:124`

Additionally, when I attempt to download a release I get the following error:

`FOF: View \Akeeba\ReleaseSystem\Site\View\Item\Zip not found /var/www/site.com/libraries/fof40/Factory/BasicFactory.php:321`

Is it supposed to work the way I updated it?

I would appreciate any help.

**Comment by nikosdion** [comment]
Oof, you'er trying to straddle a **very** big gap in releases. As a general rule, I only include code to upgrade from one major version to the next. Straddling two major releases there might not be code to do the migration.

Clarification: there is always code to upgrade the _database schema_. This is a guarantee. What is not guaranteed is having code to remove obsolete files which might otherwise get in the way of new versions e.g. because old files autoload with priority over the new version's files.

That said, it IS possible to migrate your site. Hold on to your hat, it's gonna be quite the ride.

First delete the administrator/components/com_ats, components/com_ats and media/com_ats folders. Then upgrade (or reinstall) ATS 6. At that point you only have the correct files for ATS 6 and no leftovers from ATS 4. Plugins and modules do not suffer the same problem as the component so no worries there.

The next thing to consider is that ARS 6 is running on FOF 4 and FEF 2 whereas ARS 4 is running on FOF 3 and FEF 1. This means that _all_ of your template overrides need a rewrite. That's why the frontend appeared to be broken. You might be tempted to address that. However, **do not** do that just yet if you are upgrading to Joomla 4! It would be a futile effort.

After upgrading to Joomla 4 upgrade ARS to version 7. This version of ARS does not use FOF or FEF. It only uses Joomla MVC and Bootstrap 5. You _can_ upgrade from ARS 6 to 7 directly. After the upgrade redo all your template overrides from scratch. There is such a massive difference between ARS 4 and 7 that you can't really keep any part of your existing overrides.

Following these instructions you keep the categories, releases and items, the automatic item descriptions, the environment (minus the images; these were dropped in ARS 6), the download history and the download IDs. This is the important stuff you need to keep through the migration. You do lose all template overrides but that's not a big deal since you'll very likely have to rethink them considering how old your previous ARS version is.

**Comment by tassosm** [comment]
Since the site is not ready to upgrade to J4 yet, I am attempting to update to ARS6 first.

I removed the administrator/components/com_ars, components/com_ars, and media/com_ars folders and installed the pkg_ars-6.0.3.zip package. Now, I get the following in both backend and frontend.

```
Component not found.
/Volumes/Work/www/tassos/libraries/src/Component/ComponentHelper.php:367
```

Went to Extensions -> Manage -> Discover, clicked Discover and Akeeba Release showed up. I clicked Install. Joomla reported the installation was successful, but the extension still does not work. It remains in the Discover Extensions list too.

I verify the update process has copied the component's files to administrator/components/com_ars and components/com_ars folders.

**Comment by nikosdion** [comment]
Something looks broken on your local site. Are you sure you can install any other component? It sounds like your #__extensions table doesn't have the autonumber attribute in its id column, making it impossible for Joomla to install extensions.

**Comment by tassosm** [comment]
I am sure I can install other extensions and the #__extensions table looks fine. 

And it appears com_ars got a new ID in the #__extensions table after the update.

**Comment by nikosdion** [comment]
I really don't know what is going on with your site. I have tried installing ARS 6.0.3 on a number of sites:
* A test site I use for test installing software before release
* An older copy of Akeeba.com upgraded to Joomla 3.10.10
* A brand new Joomla 3.10.10 installation

No problems.

The AkeebaFEFHelper not found problem would mean that Akeeba FEF is note installed or cannot be loaded. However, it's part of the distribution ZIP package. Extract it and install the FEF and FOF packages manually.

The problem about component not found means that there is no `#__extensions` record for com_ars. This cannot happen if the component installs successfully. Moreover, you said that the database record does exist, so why the heck does Joomla NOT see it?

Here is what I would try.

Make sure PHP's OPcache is **DISABLED**. Remember that Joomla still sucks hairy balls updating software when the opcache.invalidate_freq is more than 2, basically.

Set the site to Debug mode.

Turn off all caching.

Clear all backend and frontend cache.

Install the package twice in a row, without uninstalling anything before or in between.

Clear all backend and frontend cache, AGAIN. Remember that even with caching turned off Joomla still caches the ListModel query results and some internal stuff... including the list of components and active plugins.

**Comment by tassosm** [comment]
The solution was to set the site to Debug mode. WTF? 😀

The error `Class 'AkeebaFEFHelper' not found` fixed by switching the **Load Akeeba FEF** option in the extension's configuration from "Backend Only" to "Both". I was using this option for a long time.

The backend works flawlessly now. However, I am still facing issues on the front end. 

I have a **Normal releases** menu type. It fetches all the available releases but when I click to view all the available versions in a category, I get the following error: 

`Class 'FOF40\Container\Container' not found /Volumes/Work/www/tassos/components/com_ars/router.php:1389`

I tried to create a menu type Category for a particular Akeeba Release Category but it did not help.

Also, I have a **Akeeba Release System - My Downloads** module setup with specific Stream IDs. There, when I click to download a release, I get the following error:

`FOF: View \Akeeba\ReleaseSystem\Site\View\Item\Zip not found
/Volumes/Work/www/tassos/libraries/fof40/Factory/BasicFactory.php:321`

I get the same error with a newly created **Entire repository** menu type.

Keep in mind that I have all my overrides temporarily removed while I am troubleshooting (in case I have outdated code in there). Moreover, I re-installed lib_fof40.zip multiple times. I also removed the folder "fof40" before the re-installation attempts.

FOF40 appears as file_fof40 in the Extensions -> Manage list. Is that normal?

I would appreciate it if you could shed some more light here on what could be possibly wrong with my installation.

**Comment by nikosdion** [comment]
> The solution was to set the site to Debug mode. WTF? 😀

You definitely had a caching issue there. When using Debug mode the cache for `#__extensions` records is not used. Therefore Joomla sees the real database data and sees that the component is, in fact, installed.

> The error Class 'AkeebaFEFHelper' not found fixed by switching the Load Akeeba FEF option in the extension's configuration from "Backend Only" to "Both". I was using this option for a long time.

Ah! The frontend Dispatcher always goes through AkeebaFEFHelper. If you're not using FEF in the frontend the class is not loaded and results in an error. Next time please set your Debug Site to Yes and give me the full trace, it'd be easier to troubleshoot.

You can fix the problem by setting Use FEF to Only Backend and edit the components/com_ars/Dispatcher/Dispatcher.php. Change

```php
	private function loadCommonJavascript(): void
	{
		\AkeebaFEFHelper::loadFEFScript('Tooltip');
	}
```

to

```php
	private function loadCommonJavascript(): void
	{
		if (!in_array($this->container->params->get('load_fef', 3), [1, 3]))
		{
			return;
		}
		
		\AkeebaFEFHelper::loadFEFScript('Tooltip');
	}
```

Note that you'll have to implement an alternate tooltip script in your template overrides — if you want tooltips, that is.

> Class 'FOF40\Container\Container' not found /Volumes/Work/www/tassos/components/com_ars/router.php:1389

Open the file `components/com_ars/router.php` and add the following before the class declaration:

```php
if (!defined('FOF40_INCLUDED') && !@include_once(JPATH_LIBRARIES . '/fof40/include.php'))
{
	throw new RuntimeException('FOF 4.0 is not installed', 500);
}
```

I was only using that version of ARS on my site where other system plugins had already loaded FOF by the time Joomla tried to use the router class so I'd never caught this problem until now.

**Comment by tassosm** [comment]
Everything is working pretty well now except that all ARS SEF URLs have ?format=html at the end. 

Can I get rid of it somehow?

**Comment by nikosdion** [comment]
I believe that you have not enabled the “Add Suffix to URL” option in Global Configuration. ARS is designed to be used with that option turned on.

**Comment by tassosm** [comment]
Yes, it's disabled and I would like to keep it that way.

If I enable it, I will need to add canonical tags to all pages to prevent duplicate content as the pages will be both accessible with and without the .html suffix. A critical SEO issue. 

Secondly, I just don't like the .html suffix on my URLs 🙂

I guess I can live with it if there's no workaround.

**Comment by nikosdion** [comment]
> A critical SEO issue.

A silly SEO **myth**. 

This has not been the case since 2011.

> Secondly, I just don't like the .html suffix on my URLs 🙂

That's a different thing altogether.

> I guess I can live with it if there's no workaround.

You'll have to. There is no workaround, indeed.

**Comment by tassosm** [comment]
ARS updated to 6.0.3 successfully.

One of the reasons I wanted to update ARS, is that I was/am facing downtimes (504 timeout errors). I don't blame ARS, I just wanted to ensure it's not it. However, after the e-update, the downtimes are more frequent.

While I am investigating the culprit, I tried enabling PHP-FPM to log slow scripts that take 10+ sec. The log reports the following script countless times.

https://pastebin.com/raw/W2WLJGB2

Additionally, another issue I noticed is that all XML Stream Feeds are generated every time I access them in the browser. I can confirm this by the comment  `<!-- Generated by Akeeba Release System on 2022-08-23 14:54:53 GMT -->` and that it takes 4-5 secs to load. Shouldn't be cached?

I am aware that I am using an outdated version of your software and that I might be facing an issue/bug that you've already fixed in an earlier version of ARS.

**Comment by nikosdion** [comment]
> Shouldn't be cached?

No. You are NOT supposed to put the ARS XML stream URL in your XML manifest. You are supposed to manually upload the generated feed to a CDN and use that URL in the XML manifest.

This is a deliberate choice. Already in 2011 I had enough users that both Joomla's caching AND statically delivering the file from my own site would bring the server to its knees. It only got worse from there. So instead of wasting my time with an unsolvable problem I am just using a CDN. Considering I am serving dozens of gigabytes of update files every day I would say that was the only sane choice.

**Comment by tassosm** [comment]
I am speechless. I have the ARS XML stream URL in my XML manifest all these years and I thought it was always served cached. 

This must be the culprit.

So, what's the purpose of the XML Stream Feed menu type? For internal use only?

**Comment by nikosdion** [comment]
> I have the ARS XML stream URL in my XML manifest all these years and I thought it was always served cached.

This has not been the case in any released version of ARS.

> So, what's the purpose of the XML Stream Feed menu type? For internal use only?

Correct.

**Comment by tassosm** [comment]
Thank you for your help. I am closing the issue.
