### ISSUE TITLE
[Question] include into download logs software downloaded with Download id

### ISSUE THREAD

**Issue by kulbabskyy** [akeeba/release-system#216]
Hi, currently in the download log we have only the software that is downloaded from the repository.
Items that downloaded with the Download key is not included in the logs. 
It is possible to add the option to include those kind of download event in the download log?

Thank you.

**Comment by nikosdion** [comment]
Thank you for your report! I have fixed it in the commit https://github.com/akeeba/release-system/commit/5877c031a1e094fb26bd9d567842608b0e8efece

Tomorrow I will tag version 7.1.0.

**Comment by kulbabskyy** [comment]
Hi [Nicholas](https://github.com/nikosdion), thank you for the reply, i applied that commit, now the log is shown, but can we display also the key (instead the link) in the log that was used for update? This will allow to monitor illegal download keys usage shared with third-party persons.


![Screenshot_6](https://user-images.githubusercontent.com/37491336/203138166-acb61844-1179-4354-a635-7608f17e7751.png)

**Comment by nikosdion** [comment]
No, I will not do that. Storing a key (even an expired, removed, or mistyped one) is a potential security issue.

There is also no operational need to do so as the corrective action is very well defined, regardless of why the download failed: the user needs to get a key from the Add-on Download Keys page in the frontend and apply it to their software, then reload the update information in Joomla.

**Comment by kulbabskyy** [comment]
This will allow to monitor illegal download keys usage shared with third-party persons. Also we can hide a part of the stored key in the download logs under the stars.

**Comment by nikosdion** [comment]
No, it will not help with that, at all. Remember that I've invented the whole extension update and download key for paid updates _in Joomla_ 😉 

Active, valid keys distributed against your Terms of Service are indistinguishable from legitimate usage. You cannot tell in any sensible manner if someone has 100 sites or if they're sharing a key with 100 other people. 

An add-on download key being used by multiple IPs does not mean it's shared against your ToS, either. It is typical for web agencies to create one key _per client_, not per site. A client can have one site, dozens of sites, or anything in between.

Keys which have been deleted or unpublished, or the corresponding user rights removed, do NOT automatically mean that the site owner using them is pirating your software. The software might have had a key installed by their site integrator who later decided to cut them off as a client, or went out of business, or had other reasons to reset, unpublish, or delete a download ID. Treating these people as de facto pirates instead of potential clients is counter-productive to say the least.

Even if you had a magic crystal ball to divine which are the non-compliant uses of a Download ID you only get an IP address. So what? There could be dozens if not thousands of sites in a single IP address. Are you going to block the entire IP address which will more likely than not include some of your existing or future clients?

Besides, if you are so worried about this matter you can always extract the download IDs from your server's access logs (hint hint wink wink). You have a date, time and IP address in the ARS log. You can trivially correlate it with your access log if you are so inclined. I just want you to be fully aware that you **shouldn't** because you'll be too tempted to do something rash and ultimately against your best interests.

**Comment by kulbabskyy** [comment]
Thank you for the detailed description. In facts you are right, customer can change the key any time he want. So this will not give us nothing. Actually i do not want to ban users or IP`s. I want just to see the update system usage. Some time its very helpful while supporting customer tickets.  
The last question: if it possible to store the website domain that has accessed the update API with Download ID?

**Comment by nikosdion** [comment]
> if it possible to store the website domain that has accessed the update API with Download ID?

No. Joomla makes the request directly from the server. We do not get an HTTP Referer header, we only have the IP address the request came from.

**Comment by kulbabskyy** [comment]
ok, thank you for your time.
