### ISSUE TITLE
Undefined property stdClass::$body in helpers/amazons3.php on line 1411

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#67]
When creating categories with a CLI script that hooks up to Amazon S3, getting the below output in my terminal.

```sh
Notice: Undefined property: stdClass::$body in /administrator/components/com_ars/helpers/amazons3.php on line 1411

Call Stack:
    0.0016     274912   1. {main}() /cli/ars-populate-downloads.php:0
    0.0120     864712   2. JApplicationCli->execute() /cli/ars-populate-downloads.php:452
    0.0120     865248   3. ImportDownloads->doExecute() /libraries/joomla/application/cli.php:163
    0.1618    6744360   4. F0FModel->save() /cli/ars-populate-downloads.php:436
    0.1680    6907472   5. F0FTable->save() /libraries/f0f/model/model.php:1443
    0.1682    6908848   6. ArsTableCategory->check() /libraries/f0f/table/table.php:3537
    0.1722    7305272   7. ArsHelperAmazons3::getBucket() /administrator/components/com_ars/tables/category.php:114
    0.1722    7309584   8. ArsHelperS3Request->getResponse() /administrator/components/com_ars/helpers/amazons3.php:886
    0.1723    7313640   9. curl_exec() /administrator/components/com_ars/helpers/amazons3.php:1347
    1.4502    7315440  10. ArsHelperS3Request->__responseWriteCallback() /administrator/components/com_ars/helpers/amazons3.php:1347
```

Code I'm using to generate the categories (only includes one piece out of this massive array):

```php
// Use the F0F Platform to get all of our data
$platform = F0FPlatform::getInstance();

// Get a user object for my account
$user = $platform->getUser('michael.babker');

// ID: 4
$category = array(
	'title' => 'Joomla! 3',
	'alias' => 'joomla3',
	'description' => '<p>Category containing all official Joomla! 3 releases.</p>',
	'type' => 'normal',
	'directory' => 's3://joomladownloads/joomla3',
	'vgroup_id' => '1'
),

// Add additional data for the record
$category = array_merge($category, array('created_by' => $user->id));

// Reset the table cache on each iteration
F0FTable::forceInstance();

/** @var ArsModelCategories $categoriesModel */
$categoriesModel = F0FModel::getTmpInstance('Categories', 'ArsModel');
$categoriesModel->save($category);

if ($categoriesModel->getErrors())
{
	foreach ($categoriesModel->getErrors() as $error)
	{
		var_dump($error);
	}
}
```

**Comment by nikosdion** [comment]
It seems that you don’t have read privileges for the bucket or there’s a server firewall preventing you from connecting to Amazon S3. Another possibility –which I’m not entirely convinced about– is that you are using a bucket in an S3 region which does not support the AWSv2 authentication API, i.e. Frankfurt or Sao Paolo.=

**Comment by mbabker** [comment]
I guess Brad set some level of security up on the bucket then.  Same keys on my local and the dev site, the dev site doesn't throw that message but local does.  FWIW, dev site is showing a `Notice: curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in administrator/components/com_ars/helpers/amazons3.php on line 1241` message though.

**Comment by nikosdion** [comment]
The CURLOPT_SSL_VERIFYHOST warning is expected. Due to problems in the (very old) S3 library I'm using I am trying to only match the SSL certificate's common name (value 1) instead of both the CN and hostname. At some point I'll replace that library with the bugfixed Amazon AWS SDK for PHP –the original has a bug in Guzzle I PR'd to get it fixed– and this notice will go away. Time. I need another 24 hours in my day!

Hm, since you get this on just the dev site I'd recommend taking a look at your local server's OpenSSL version. If you've got OpenSSL 0.9.x which is the default for Macs you're out of luck, amigo: it doesn't support SHA-256 signed certificates. You'll need to use a Linux server with a recent OpenSSL version in the 1.0.x range. The Vagrant box recipe I've got on GitHub does produce a compatible server if you're wondering.
