### ISSUE TITLE
moredummy?

### ISSUE THREAD

**Issue by anibalsanchez** [akeeba/release-system#77]
Hi,

I have just found that download Urls ending with dummy=my.zip are not longer generating files ended with .zip. In the installer plugin, I have added a new moredummy=my.zip after dlid to fix it.

Is this the current best practice?

**Comment by nikosdion** [comment]
Can you try explaining what you mean? What you wrote doesn't make much sense. Exactly what you did. Exactly what you got. Why you think it's not the expected result.

**Comment by anibalsanchez** [comment]
Yes, sorry, my writing is mumble jumble ... Again:

From a XML Update stream generated with ars-2.5.0. Urls are generated in this way:

	<downloadurl type="full" format="zip">http://www.mydomain.com/update.html?view=download&amp;id=327&amp;dummy=my.zip</downloadurl>

dummy=my.zip was working perfectly fine, allowing Joomla installer to download and unpack the package. It was working for a public download and for a restricted download (where installer plugin adds dlid).

After received customer reports, I have just verified that it is downloading this file:

tmp/update.html?view=download&id=327&dummy=my.zip&dlid=a2blablalblalblablalblabla4a

dummy parameter introduced to generate files with zip extension is not working as before. I have just modified the installer plugin to also add a moredummy parameter to the Url:

		// Appent the Download ID to the download URL
		if (!empty($dlid))
		{
			$uri->setVar('dlid', $dlid);
			$url = $uri->toString();
		}

		$uri->setVar('moredummy', 'my.zip');
		$url = $uri->toString();

Is this a known issue?

**Comment by nikosdion** [comment]
I still don't understand what is the difference you are talking about.

**Comment by anibalsanchez** [comment]
It was previously working fine with dummy=my.zip (as it is generated in views/update/tmpl/stream.php), but now it does not work and installer plugin has to add moredummy=my.zip parameter after dlid definition.

Looking for the problem source, it is related with this change https://github.com/akeeba/release-system/commit/8958c1341cceb25d72254cb4218034db3c5cd724#diff-7fe0a085f3cb249c0024e0f7097a960bL40

Before the change, dlid was always defined in the Url ending with zip.

http://www.mydomain.com/update.html?view=download&amp;id=327&amp;dlid=&amp;dummy=my.zip

So, JUri was receiving dlid empty parameter into a middle position. When JUri was called by installer plugin, it was replacing the empty string in that position. But, now, dlid param is not present and it is added at the Url end. In this was, final Url does not longer end with .zip. 

Thus, dummy=my.zip is only for public downloads and restricted downloads require installer plugin to also add a moredummy.

In my opinion, stream.php has to keep the empty dlid definition to solve both cases in the same way:

	$dlid = trim($this->input->getCmd('dlid', ''));

	if (!empty($dlid))
	{
		$this->loadHelper('filter');
		$dlid = ArsHelperFilter::reformatDownloadID($dlid);
	}

        // Parameter is always defined to keep Url ext ending
	$dlid = '&dlid='.$dlid;

	// Clear everything before starting the output
	@ob_end_clean();

**Comment by nikosdion** [comment]
So, you want me to reintroduce a bug in ARS to mask a bug in your installer plugin? Ain't gonna happen.

How about doing the obvious:
Remove the dummy variable
Add the dlid variable
Add the dummy variable

Or you could use F0FUtilsUpdate which makes use of Joomla! 3.2+ extra_query field in the database to add the dlid=something query string parameter. Better yet, Joomla! doesn't take it into account when determining the file type of the downloaded type. I contributed that feature and deliberately made it this way to –guess what?– work around any possible issues similar to the one you're describing.

FYI the installer plugins feature were a notoriously bad idea implemented AFTERWARDS by the people who wrote the now dead as a dodo "Install from Web" feature. They were supposed to act as a bridge for downloading paid extensions through the "Install from Web" feature if the developer was willing to insert his head so far up his ass that it came over the top again, jump through undocumented hoops and base their business model on a precarious integration which of course died due to the impossibility of maintaining it reasonably.

In so many words: don't use installer plugins. You only "have" to use them if you support Joomla! 2.5 which is also dead as a dod. If you expect to keep on supporting obsolete platforms using integrations based on bad ideas be prepared to write two extra lines of code in about one hundredth of the time we both spent replying back and forth on this (non-)issue.

**Comment by anibalsanchez** [comment]
Ok, no problem. I was just looking for a way to keep it working as before.

If this is the best way for Joomla! 3.2+, it is perfectly fine for me. I did't know the full detail. I am planning to drop J25 support in the next major versions. I'm taking notes to adopt F0FUtilsUpdate asap.

Case solved. Best Regards.
